### ISSUE TITLE
history, or edit log?

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#18]
Now that we have edit tree (yay :fireworks: ) there are suddenly ways to be more destructive to the db. We don't store any historic data of a tree, nor is there any edit log. What do we think about that?

(deletion is currently different, since it just marks a tree as deleted).

**Comment by rotsee** [comment]
Some thoughts:

1. We could treat edits as deletion + new tree, thereby utilizing the current setup, where deletions are logged. A bit awkward, and the tree table could grow considerably, though

2. We could store all tree revisions as separate trees in the db, but flagged as ”old”. Semantically cleaner than 1, but with the same drawbacks. The tree table would soon be very big.

3. We could implement a _real_ revision history system. This would be a quite different db layoyut, maybe with one revision table, one table with all tree content, and list of current trees, or something like that.

4a. We could do nothing. During the 8 or so years Fruktkartan has been up and running, the only issues we've had with vandalism has been a few profane words. Rather than keeping all revision history in the db, we could just do regular backups. 

4b. 4a, _but_ adding an “edits” field to the tree db, storing just the ip addresses and timestamps for all edits to a tree, to be able to spot vandalism and block ip ranges if necessary.

Are there other options?

**Comment by rotsee** [comment]
A suggestion:

![image](https://user-images.githubusercontent.com/122874/76467843-d7aa9800-63ea-11ea-8e23-decc2f78922d.png)

**Comment by quite** [comment]
Yes I think number 4, and your approach there looks promising!

We could also do something completely different—triggers! I tried creating a stored procedure that is triggered to run on every data modification. Currently it stores old and new json blobs, and does thus not need any adjusting if we alter the trees table. Also, since we dont DELETE rows, our logical delete appears as an update... Otherwise it could be sound and usable? Might need some thinking through. But we're just interested in keeping a log against vandals, not visualizing anything right.

https://github.com/fruktkartan/fruktkartan/blob/historytrigger/history_trigger.sql

**Comment by quite** [comment]
I applied it to the live db for you to have a look :)

**Comment by quite** [comment]
Moved it to the api: https://github.com/fruktkartan/fruktkartan-api/blob/historytrigger/history_trigger.sql

**Comment by quite** [comment]
@rotsee did you see my experiment here? I'm thinking we should settle on something before launching...

**Comment by rotsee** [comment]
The triggers seem to work quite well, don't you think? This also means that we could actually delete deleted trees, right?

**Comment by quite** [comment]
Yes, it does. Looks like you read in a db dump on may 8th, right? And the history tables was emptied, but you have the history table/function/trigger in the schema you use now?

**Comment by quite** [comment]
And yes, deletes should be fine with this.
