### ISSUE TITLE
black frame around addnew icon in Firefox

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#30]
And I don't see any problem with the shadow when removing the shadow hack.

**Comment by rotsee** [comment]
The black frame was due to a missing file, but the hack is still there.
I can't seem to figure out why an explicit shadow is require in this particular case.

**Comment by quite** [comment]
But I see the shadow from the addnew.svg even without the hack. But yeah, now the shadow.png works, and the shadow is bigger, also extending slightly to towards bottom-left of the bubble.

**Comment by rotsee** [comment]
Yep, that's because we use the default icon shadow (we don't have a shadow image of our own).

Our problem is that our icons don't have shadow versions (or rather, their shadow is included in the icon image). For our ordinary icons we set the shadow to `null`, but for the addnew icon that does not work (for reasons I don't fully understand). For the addnew icon Leaflet will always try to use the default shadow if none provided (and because the way Vue handles images that will not work either, so we have to explicitly provide an image).

One easy workaround would be to create a shadow file, of course.

**Comment by rotsee** [comment]
To be clear: The hack is _not_ there to provide a shadow, but to avoid browsers trying to load a non-existing image. Without it, you will get an error message in Chrome, for instance
.

**Comment by quite** [comment]
OK, this was really confusing for me :) But if I set `shadowUrl: null,` I see no problem on the site, but yes there is an error in the console in chromium.

**Comment by quite** [comment]
Think we're done here for now.

**Comment by rotsee** [comment]
I fixed this for now by setting the shadow to 0x0 px.
