### ISSUE TITLE
Add ”flag for deletion” button

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktkartan#95]
The API now has a flag/unflag for deletion-endpoint (not yet on prod server, see https://github.com/fruktkartan/fruktkartan-api/pull/28), so we could add a ”flag for deletion” button where we used to have ”delete”. 

Before adding that, it would be nice to have a view for these flags in Fruktsam, where we could also delete them. What do you say, @quite?

**Comment by quite** [comment]
Yes I can imagine Fruktsam outputting trees which has been flagged for deletion, and some brutalist <script> thingy there on the otherwise static page for deleting them. But I won't have time to do it all soon.

If you've decided to go with a separate table for the deletion-flag, then once that is implemented and in prod (i think), I could begin with adding display of that in Fruktsam. It is probably useful to have that user-hash and timestamp along with the ssmkey and deletion-flag here, so the separate table is probably good.

**Comment by rotsee** [comment]
Added in `master` branch now. Would you have time to take a quick look and see if it looks ok to you, @quite?

If it does, I'd suggest doing further testing in production. I get quite a few emails every week asking be to remove trees since the delete button was removed, so I'd like to put this out there as soon as possible.

**Comment by quite** [comment]
Jag försöker markera detta träd, men nåt går snett https://master--fruktkartan.netlify.app/#/t/575225686

**Comment by quite** [comment]
Maybe that's because the new api has not been deployed to heroku prod?

**Comment by quite** [comment]
I tried running frontend and api locally now towards dev db. Stuff seems to work. I'd say deploy it all!

**Comment by rotsee** [comment]
:tada:
